masukkannamaAnda = input ('Masukkan nama Anda: ')
masukkannamamatakuliah = input ('Masukkan nama matakuliah: ')
masukkangrupAnda = input ('Masukkan grup Anda: ')
print(f'Haloo! {masukkannamaAnda}{masukkannamaAnda}')
print('Anda tergabung dalam ' + masukkannamamatakuliah + ' pada grup ' + masukkangrupAnda)